### ISSUE TITLE
Dynamic Colors

### ISSUE THREAD

**Issue by project-saf** [raymondjavaxx/ColorToolbox#15]
Does this work for dynamic colors?
e.g. the ones that return different colors depending on traits

**Comment by raymondjavaxx** [comment]
Hi @project-saf,

It does.  Methods that transform colors (i.e., `lightening(by:)` and `darkening(by:)`) return values constructed using [dynamic providers](https://github.com/raymondjavaxx/ColorToolbox/blob/526225a7140fc2e87fdad29451669d3e3efe016b/Sources/ColorToolbox/PlatformColor%2BBrightness.swift#L40-L52). So, if the original color is dynamic, the resulting color will also be dynamic. The rest of the methods and properties use the current trait collection:

```swift
let aDynamicColor = UIColor.label

print(aDynamicColor.toHex()) // -> #000000
print(aDynamicColor.relativeLuminance) // -> 0.0

UITraitCollection(userInterfaceStyle: .dark).performAsCurrent {
    print(aDynamicColor.toHex()) // -> #FFFFFF
    print(aDynamicColor.relativeLuminance) // -> 1.0
}
```
